[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["xmr4el", "xmr4el.*"]

[project]
name = "xmr4el"
version = "0.5.3"
description = "eXtreme Multi-Label Ranking for Entity Linking"
authors = [
  { name="João Vedor", email="fc56311@alunos.fc.ul.pt" }
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "joblib",
  "numpy",
  "pandas",
  "psutil",
  "scikit-learn",
  "transformers",
  "sentence-transformers",
  "faiss-cpu",
  "lightgbm",
  "umap-learn",
  "fuzzywuzzy",
  "python-Levenshtein",
  "memory_profiler",
  "biopython",

  "torch>=2.8.0",

  "kmeans-pytorch @ git+https://github.com/kernelmachine/balanced-kmeans.git@main"
]

[project.optional-dependencies]
rapids = [
  "cuml-cu12==25.*; sys_platform == 'linux'",
  "cudf-cu12==25.*; sys_platform == 'linux'",
  "rmm-cu12==25.*; sys_platform == 'linux'",
  "cupy-cuda12x>=13.6; sys_platform == 'linux'",
]
