[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["xmr4el", "xmr4el.*"]

[project]
name = "xmr4el"
version = "0.5.3"
description = "eXtreme Multi-Label Ranking for Entity Linking"
authors = [
  { name="João Vedor", email="fc56311@alunos.fc.ul.pt" }
]
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
  "joblib",
  "numpy",
  "pandas",
  "scipy",
  "scikit-learn",
  "transformers",
  "sentence-transformers",
  "faiss-cpu",
  "lightgbm",
  "umap-learn",

  "torch>=2.8.0",

  "kmeans-pytorch @ git+https://github.com/kernelmachine/balanced-kmeans.git@main"
]
